/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kinjal
 */
public class AddRestaurantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createRestaurantJPanel
     */
    private final RestaurantDirectory restaurantDirectory;
    private final JPanel container;
    private final EcoSystem system;

    public AddRestaurantJPanel(JPanel container, EcoSystem system, RestaurantDirectory restaurantDirectory) {
        initComponents();
        this.restaurantDirectory = restaurantDirectory;
        this.container = container;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddRes = new javax.swing.JLabel();
        lblResName = new javax.swing.JLabel();
        lblStreetAdd = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        txtResName = new javax.swing.JTextField();
        txtStreetAddress = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblManagerName = new javax.swing.JLabel();
        txtManagerName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblZipcode = new javax.swing.JLabel();
        txtZipcode = new javax.swing.JTextField();
        lblPhoneNo1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblRestroNameError = new javax.swing.JLabel();
        lblZipcodeError = new javax.swing.JLabel();
        lblManagerNameError = new javax.swing.JLabel();
        lblEmailError = new javax.swing.JLabel();
        lblPhoneNumberError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(null);

        lblAddRes.setBackground(new java.awt.Color(255, 153, 0));
        lblAddRes.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblAddRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddRes.setText(" Create Restaurant");
        lblAddRes.setOpaque(true);
        add(lblAddRes);
        lblAddRes.setBounds(171, 45, 390, 50);

        lblResName.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblResName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblResName.setText("Restaurant Name:");
        add(lblResName);
        lblResName.setBounds(175, 123, 87, 26);

        lblStreetAdd.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblStreetAdd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStreetAdd.setText("Street Address:");
        add(lblStreetAdd);
        lblStreetAdd.setBounds(175, 160, 87, 22);

        lblPhoneNo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblPhoneNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhoneNo.setText("Phone no:");
        add(lblPhoneNo);
        lblPhoneNo.setBounds(175, 320, 87, 22);

        txtResName.setBackground(new java.awt.Color(255, 255, 204));
        txtResName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtResNameKeyPressed(evt);
            }
        });
        add(txtResName);
        txtResName.setBounds(295, 124, 262, 26);

        txtStreetAddress.setBackground(new java.awt.Color(255, 255, 204));
        add(txtStreetAddress);
        txtStreetAddress.setBounds(295, 160, 262, 27);

        txtPhoneNo.setBackground(new java.awt.Color(255, 255, 204));
        txtPhoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneNoKeyPressed(evt);
            }
        });
        add(txtPhoneNo);
        txtPhoneNo.setBounds(295, 312, 262, 30);

        btnSave.setBackground(new java.awt.Color(255, 153, 0));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnSave.setText("Create Restaurant");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(370, 470, 130, 29);

        btnBack.setBackground(new java.awt.Color(255, 153, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(22, 577, 80, 30);

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername.setText("Username:");
        add(lblUsername);
        lblUsername.setBounds(180, 360, 87, 23);

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassword.setText("Password:");
        add(lblPassword);
        lblPassword.setBounds(180, 400, 87, 28);

        txtUsername.setBackground(new java.awt.Color(255, 255, 204));
        add(txtUsername);
        txtUsername.setBounds(295, 352, 262, 30);

        lblManagerName.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblManagerName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblManagerName.setText("Manager Name:");
        add(lblManagerName);
        lblManagerName.setBounds(175, 243, 87, 23);

        txtManagerName.setBackground(new java.awt.Color(255, 255, 204));
        txtManagerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtManagerNameKeyPressed(evt);
            }
        });
        add(txtManagerName);
        txtManagerName.setBounds(295, 236, 262, 30);

        txtPassword.setBackground(new java.awt.Color(255, 255, 204));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword);
        txtPassword.setBounds(290, 400, 270, 28);

        lblZipcode.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblZipcode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblZipcode.setText("Zipcode:");
        add(lblZipcode);
        lblZipcode.setBounds(175, 200, 87, 25);

        txtZipcode.setBackground(new java.awt.Color(255, 255, 204));
        txtZipcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtZipcodeKeyPressed(evt);
            }
        });
        add(txtZipcode);
        txtZipcode.setBounds(295, 200, 262, 25);

        lblPhoneNo1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblPhoneNo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhoneNo1.setText("Email:");
        add(lblPhoneNo1);
        lblPhoneNo1.setBounds(175, 282, 87, 13);

        txtEmail.setBackground(new java.awt.Color(255, 255, 204));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        add(txtEmail);
        txtEmail.setBounds(295, 276, 262, 26);
        add(lblRestroNameError);
        lblRestroNameError.setBounds(590, 127, 220, 20);
        add(lblZipcodeError);
        lblZipcodeError.setBounds(600, 203, 210, 20);
        add(lblManagerNameError);
        lblManagerNameError.setBounds(590, 240, 220, 20);
        add(lblEmailError);
        lblEmailError.setBounds(600, 280, 200, 20);
        add(lblPhoneNumberError);
        lblPhoneNumberError.setBounds(600, 320, 210, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtResName.getText();
        String address = txtStreetAddress.getText();
        String phone = txtPhoneNo.getText();
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String managerName = txtManagerName.getText();
        String zipcode = txtZipcode.getText();
        String email = txtEmail.getText();

        if (username.isEmpty() || password.isEmpty() || name.isEmpty() || address.isEmpty() || phone.isEmpty() || managerName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter All Fields!");
        } else if (!system.checkValidPhoneFormat(phone)) {
            JOptionPane.showMessageDialog(null, "Please Enter Valid Phone No.");
        } else if (!system.checkValidNameFormat(name)) {
            JOptionPane.showMessageDialog(null, "Please Enter Valid Name");
        } else if (!system.checkValidNameFormat(managerName)) {
            JOptionPane.showMessageDialog(null, "Please Enter Valid Manager Name");
        } else if (!system.checkValidZipcodeFormat(zipcode)) {
            JOptionPane.showMessageDialog(null, "Zipcode format incorrect! Zipcode should be 5 digits");
        } else if (!system.checkValidEmailFormat(email)) {
            JOptionPane.showMessageDialog(null, "Email format incorrect!");
        } else if (!system.getUserAccountDirectory().checkIfUsernameIsUnique(username)) {
            JOptionPane.showMessageDialog(null, "Username Already Exists!");
        } else if (!restaurantDirectory.isPhoneUnique(phone)) {
            JOptionPane.showMessageDialog(null, "Phone no Already Registered!");
        } else {
            Restaurant restaurant = new Restaurant();
            restaurant.setRestaurantName(name);
            restaurant.setStreetAddress(address);
            restaurant.setOperatorName(managerName);
            restaurant.setMobileNo(phone);
            restaurant.setEmail(email);
            restaurant.setZipcode(zipcode);
            restaurantDirectory.add(restaurant);
            system.setRestaurantDirectory(restaurantDirectory);
            Employee employee = system.getEmployeeDirectory().createEmployee(restaurant.getRestaurantNo());
            UserAccount account = system.getUserAccountDirectory().createUserAccount(username, password, employee, new AdminRole());
            JOptionPane.showMessageDialog(null, "New Restaurant has been added!");
            clearAllFields();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    public void clearAllFields() {
        txtResName.setText("");
        txtStreetAddress.setText("");
        txtPhoneNo.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtManagerName.setText("");
        txtZipcode.setText("");
        txtEmail.setText("");
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        UpdateRestaurantJPanel manageRestaurantJPanel = (UpdateRestaurantJPanel) component;
        manageRestaurantJPanel.populateRestaurants();

        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtResNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResNameKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
           
           if(Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c)){
               lblRestroNameError.setText(" ");
               txtResName.setEditable(true);
               
           }else {
               if(!Character.isLetter(c)){
              // txtName.setEditable(false);
                lblRestroNameError.setText("Enter a restaurant valid name");
               }
           }
        
    }//GEN-LAST:event_txtResNameKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
        
        String emailRegex = "^[a-zA-Z0-9]+@[a-zA-Z]+\\.[a-zA-Z]+";
        Pattern ep = Pattern.compile(emailRegex);
        Matcher matcher = ep.matcher(txtEmail.getText());
        if(!matcher.matches())
        {
        lblEmailError.setText("Email ID is not valid");
        }
        else
        {
            lblEmailError.setText(null);
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtPhoneNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNoKeyPressed
        // TODO add your handling code here:
        
        String phoneNo = txtPhoneNo.getText();
        int length = phoneNo.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<10){
                txtPhoneNo.setEditable(true);
                lblPhoneNumberError.setText("Phone Number should be 10 digits!!");
            }else{
                txtPhoneNo.setEditable(false);
                lblPhoneNumberError.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtPhoneNo.setEditable(true);
               
            }else{
                txtPhoneNo.setEditable(false);  
            }
        }
    }//GEN-LAST:event_txtPhoneNoKeyPressed

    private void txtZipcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZipcodeKeyPressed
        // TODO add your handling code here:
        
        String zipcode = txtZipcode.getText();
        int length = zipcode.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<5){
                txtZipcode.setEditable(true);
                lblZipcodeError.setText("zipcode Number should be 5 digits!!");
            }else{
                txtZipcode.setEditable(false);
                lblZipcodeError.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtZipcode.setEditable(true);
               
            }else{
                txtZipcode.setEditable(false);  
            }
        }
    }//GEN-LAST:event_txtZipcodeKeyPressed

    private void txtManagerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManagerNameKeyPressed
        // TODO add your handling code here:
        
        char c =evt.getKeyChar();
           
           if(Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c)){
               lblManagerNameError.setText(" ");
               txtManagerName.setEditable(true);
               
           }else {
               if(!Character.isLetter(c)){
              // txtName.setEditable(false);
                lblManagerNameError.setText("Enter a restaurant valid name");
               }
           }
    }//GEN-LAST:event_txtManagerNameKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAddRes;
    private javax.swing.JLabel lblEmailError;
    private javax.swing.JLabel lblManagerName;
    private javax.swing.JLabel lblManagerNameError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblPhoneNo1;
    private javax.swing.JLabel lblPhoneNumberError;
    private javax.swing.JLabel lblResName;
    private javax.swing.JLabel lblRestroNameError;
    private javax.swing.JLabel lblStreetAdd;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JLabel lblZipcodeError;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtManagerName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtResName;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtZipcode;
    // End of variables declaration//GEN-END:variables
}
