/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.Menu.Item;
import Business.Menu.MenuDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Charmi Dalal
 */
public class RestaurantMenuItemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RestaurantMenuItemJPanel
     */
    private final JPanel container;
    private final Item item;
    private final MenuDirectory menuDirectory;
    
    public RestaurantMenuItemJPanel(JPanel container,Item item, MenuDirectory menuDirectory) {
        initComponents();
        this.container = container;
        this.item = item;
        this.menuDirectory = menuDirectory;
        txtItemName.setText(item.getItemName());
        txtIngrediants.setText(item.getIngrediants());
        txtItemPrice.setText(String.valueOf(item.getPrice()));
        txtItemNo.setText(item.getItemNo());
        restrictEditOnFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUpdateMenuItem = new javax.swing.JLabel();
        txtItemNo = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        txtIngrediants = new javax.swing.JTextField();
        txtItemPrice = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblItemNo = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        lblIngrediants = new javax.swing.JLabel();
        lblItemPrice = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        lblUpdateMenuItem.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblUpdateMenuItem.setText("Update Menu Item");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblItemNo.setText("Item No:");

        lblItemName.setText("Item Name:");

        lblIngrediants.setText("Ingrediants:");

        lblItemPrice.setText("Item Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblItemName)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblItemPrice)
                                        .addComponent(lblItemNo)
                                        .addComponent(lblIngrediants)))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtItemName, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txtItemNo)
                                    .addComponent(txtIngrediants)
                                    .addComponent(txtItemPrice)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addGap(60, 60, 60)
                                .addComponent(btnSave)
                                .addGap(45, 45, 45)
                                .addComponent(btnBack))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(lblUpdateMenuItem)))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblUpdateMenuItem)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItemNo)
                    .addComponent(txtItemNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItemName))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngrediants)
                    .addComponent(txtIngrediants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItemPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(108, 108, 108))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String itemNo = txtItemNo.getText();
        String itemName = txtItemName.getText();
        String ingrediants = txtIngrediants.getText();
        Double price = 0.0;
        try{
            price  = Double.parseDouble(txtItemPrice.getText());
        } catch(NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Enter Valid Price!");
        }
       
        if(itemNo.isEmpty() || itemName.isEmpty() || ingrediants.isEmpty() || price == 0.0){
            JOptionPane.showMessageDialog(null, "Please Fill All Fields!");
        }
        else{
            menuDirectory.updateItem(item.getItemNo(),itemName,ingrediants,price);
            restrictEditOnFields();
            JOptionPane.showMessageDialog(null, "Menu item successfully!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtItemName.setEditable(true);
        txtIngrediants.setEditable(true);
        txtItemPrice.setEditable(true);
    }//GEN-LAST:event_btnUpdateActionPerformed
    public void restrictEditOnFields(){
        txtItemName.setEditable(false);
        txtItemNo.setEditable(false);
        txtIngrediants.setEditable(false);
        txtItemPrice.setEditable(false);
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RestaurantMenuJPanel manageMenuJPanel = (RestaurantMenuJPanel) component;
        manageMenuJPanel.populateMenu();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblIngrediants;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblItemNo;
    private javax.swing.JLabel lblItemPrice;
    private javax.swing.JLabel lblUpdateMenuItem;
    private javax.swing.JTextField txtIngrediants;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemNo;
    private javax.swing.JTextField txtItemPrice;
    // End of variables declaration//GEN-END:variables
}
