/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.CarDetails;
import model.CarDetailsHistory;

/**
 *
 * @author kinjal
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    
    CarDetailsHistory carDetailsHistory;
    
    public SearchJPanel(CarDetailsHistory carDetailsHistory) {
        initComponents();
        this.carDetailsHistory = carDetailsHistory;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchCarDetails = new javax.swing.JTable();
        lblCreateTitle = new javax.swing.JLabel();
        lblSearchCarAvailability = new javax.swing.JLabel();
        txtSearchNumSeats = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnSearchCarManufacturer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblSearchCarModelName = new javax.swing.JLabel();
        txtSearchCarModelName = new javax.swing.JTextField();
        lblSearchCarModelNum = new javax.swing.JLabel();
        txtSearchCarModelNum = new javax.swing.JTextField();
        lblYearOfManufacturing = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        txtSearchYearOfManufacturing = new javax.swing.JTextField();
        txtSearchCarManufacturer = new javax.swing.JTextField();
        lblNumSeats = new javax.swing.JLabel();
        txtSearchSerialNumber = new javax.swing.JTextField();
        lblSearchCarAvailability1 = new javax.swing.JLabel();
        txtSearchCarAvailability = new javax.swing.JTextField();
        txtSearchCarMainCertiExpiry = new javax.swing.JTextField();
        btnSearchCarModelNum = new javax.swing.JButton();
        btnSearchYearOfManufacturing = new javax.swing.JButton();
        btnSearchSerialNumber = new javax.swing.JButton();
        btnSearchCarMainCertiExpiry = new javax.swing.JButton();
        btnCarAvailability = new javax.swing.JButton();
        btnSearchCarModelName = new javax.swing.JButton();
        btnSearchNumSeats = new javax.swing.JButton();
        lblSerialNumber1 = new javax.swing.JLabel();
        txtSearchLocation = new javax.swing.JTextField();
        btnSearchLocation = new javax.swing.JButton();
        btnSearchFirstCarAvailable = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));

        tblSearchCarDetails.setBackground(new java.awt.Color(204, 204, 204));
        tblSearchCarDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car Manufacturer", "Car Model Name", "Car Model Number", "Car Manufacturing Year", "Serial Number", "Location", "Number Of Seats", "Availability", "Maintenance Certificate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSearchCarDetails.setPreferredSize(new java.awt.Dimension(1000, 800));
        jScrollPane1.setViewportView(tblSearchCarDetails);

        lblCreateTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCreateTitle.setForeground(new java.awt.Color(0, 0, 204));
        lblCreateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateTitle.setText("View Car Details");

        lblSearchCarAvailability.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblSearchCarAvailability.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSearchCarAvailability.setText("Search Car Availability :");

        txtSearchNumSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchNumSeatsActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Display All Records");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSearchCarManufacturer.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSearchCarManufacturer.setText("Search");
        btnSearchCarManufacturer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchCarManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCarManufacturerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Search Car Manufacturer :");

        lblSearchCarModelName.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblSearchCarModelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSearchCarModelName.setText("Search Model Name :");

        lblSearchCarModelNum.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblSearchCarModelNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSearchCarModelNum.setText("Search Model Number :");

        lblYearOfManufacturing.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblYearOfManufacturing.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYearOfManufacturing.setText("Search Car Manufacturing Year :");

        lblSerialNumber.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNumber.setText("Search Serial  Number :");

        txtSearchYearOfManufacturing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchYearOfManufacturingKeyPressed(evt);
            }
        });

        txtSearchCarManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchCarManufacturerActionPerformed(evt);
            }
        });

        lblNumSeats.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblNumSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumSeats.setText("Search Number of Seats :");

        lblSearchCarAvailability1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblSearchCarAvailability1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSearchCarAvailability1.setText("Search Expired car Maintenance Certificate :");

        btnSearchCarModelNum.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSearchCarModelNum.setText("Search");
        btnSearchCarModelNum.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchCarModelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCarModelNumActionPerformed(evt);
            }
        });

        btnSearchYearOfManufacturing.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSearchYearOfManufacturing.setText("Search");
        btnSearchYearOfManufacturing.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchYearOfManufacturing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchYearOfManufacturingActionPerformed(evt);
            }
        });

        btnSearchSerialNumber.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSearchSerialNumber.setText("Search");
        btnSearchSerialNumber.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSerialNumberActionPerformed(evt);
            }
        });

        btnSearchCarMainCertiExpiry.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSearchCarMainCertiExpiry.setText("Search");
        btnSearchCarMainCertiExpiry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchCarMainCertiExpiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCarMainCertiExpiryActionPerformed(evt);
            }
        });

        btnCarAvailability.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnCarAvailability.setText("Search");
        btnCarAvailability.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCarAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarAvailabilityActionPerformed(evt);
            }
        });

        btnSearchCarModelName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSearchCarModelName.setText("Search");
        btnSearchCarModelName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchCarModelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCarModelNameActionPerformed(evt);
            }
        });

        btnSearchNumSeats.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSearchNumSeats.setText("Search");
        btnSearchNumSeats.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchNumSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNumSeatsActionPerformed(evt);
            }
        });

        lblSerialNumber1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblSerialNumber1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNumber1.setText("Search Location :");

        btnSearchLocation.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSearchLocation.setText("Search");
        btnSearchLocation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLocationActionPerformed(evt);
            }
        });

        btnSearchFirstCarAvailable.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSearchFirstCarAvailable.setText("First Available Car");
        btnSearchFirstCarAvailable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchFirstCarAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFirstCarAvailableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearchFirstCarAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSearchCarModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchCarModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYearOfManufacturing, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerialNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchCarAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchCarAvailability1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearchCarModelName)
                    .addComponent(txtSearchCarModelNum)
                    .addComponent(txtSearchYearOfManufacturing)
                    .addComponent(txtSearchCarManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(txtSearchSerialNumber)
                    .addComponent(txtSearchLocation)
                    .addComponent(txtSearchNumSeats)
                    .addComponent(txtSearchCarAvailability)
                    .addComponent(txtSearchCarMainCertiExpiry))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchCarModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCarManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCarModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchYearOfManufacturing, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchNumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCarMainCertiExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCreateTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblCreateTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchFirstCarAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchCarManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchCarManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSearchCarModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtSearchCarModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearchCarModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchCarModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCarModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchCarModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchYearOfManufacturing, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchYearOfManufacturing, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYearOfManufacturing, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtSearchSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchNumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchNumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchCarAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchCarAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchCarAvailability1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchCarMainCertiExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCarMainCertiExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchCarManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCarManufacturerActionPerformed
        // TODO add your handling code here:
        
        String carManufacturer = txtSearchCarManufacturer.getText();
       
        DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
        model.setRowCount(0);
        int count =0;
        for(CarDetails carDetails : carDetailsHistory.getCarDetailsHistory()){

         if(carDetails.getCarManufacturer().equals(carManufacturer)){
             count++;
             Object[] row = new Object[9];
             row[0]= carDetails;
             row[1]= carDetails.getCarModelName();
             row[2]= carDetails.getCarModelNum();
             row[3]= carDetails.getYearOfManufacturing();
             row[4]= carDetails.getSerialNumber();
             row[5]= carDetails.getLocation();
             row[6]= carDetails.getNumSeats();
             row[7]= carDetails.getCarAvailability();
             row[8]= carDetails.getMainCertiExpiry();

             model.addRow(row);
         }
        }
    }//GEN-LAST:event_btnSearchCarManufacturerActionPerformed

    private void txtSearchYearOfManufacturingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchYearOfManufacturingKeyPressed
        // TODO add your handling code here 
    }//GEN-LAST:event_txtSearchYearOfManufacturingKeyPressed

    private void txtSearchCarManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchCarManufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchCarManufacturerActionPerformed

    private void btnSearchCarModelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCarModelNumActionPerformed
        // TODO add your handling code here:
        
        String carModelNum = txtSearchCarModelNum.getText();
       
        DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
        model.setRowCount(0);
        int count =0;
        for(CarDetails carDetails : carDetailsHistory.getCarDetailsHistory()){

         if(carDetails.getCarModelNum().equals(carModelNum)){
             count++;
             Object[] row = new Object[9];
             row[0]= carDetails;
             row[1]= carDetails.getCarModelName();
             row[2]= carDetails.getCarModelNum();
             row[3]= carDetails.getYearOfManufacturing();
             row[4]= carDetails.getSerialNumber();
             row[5]= carDetails.getLocation();
             row[6]= carDetails.getNumSeats();
             row[7]= carDetails.getCarAvailability();
             row[8]= carDetails.getMainCertiExpiry();

             model.addRow(row);
         }
        }
    }//GEN-LAST:event_btnSearchCarModelNumActionPerformed

    private void btnSearchYearOfManufacturingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchYearOfManufacturingActionPerformed
        // TODO add your handling code here:
        
        String yearOfManufacturing = txtSearchYearOfManufacturing.getText();
       
        DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
        model.setRowCount(0);
        int count =0;
        for(CarDetails carDetails : carDetailsHistory.getCarDetailsHistory()){

         if(carDetails.getYearOfManufacturing().equals(yearOfManufacturing)){
             count++;
             Object[] row = new Object[9];
             row[0]= carDetails;
             row[1]= carDetails.getCarModelName();
             row[2]= carDetails.getCarModelNum();
             row[3]= carDetails.getYearOfManufacturing();
             row[4]= carDetails.getSerialNumber();
             row[5]= carDetails.getLocation();
             row[6]= carDetails.getNumSeats();
             row[7]= carDetails.getCarAvailability();
             row[8]= carDetails.getMainCertiExpiry();

             model.addRow(row);
         }
        }
    }//GEN-LAST:event_btnSearchYearOfManufacturingActionPerformed

    private void btnSearchSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSerialNumberActionPerformed
        // TODO add your handling code here:
        
        String serialNumber = txtSearchSerialNumber.getText();
       
        DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
        model.setRowCount(0);
        int count =0;
        for(CarDetails carDetails : carDetailsHistory.getCarDetailsHistory()){

         if(Integer.toString(carDetails.getSerialNumber()).equals(serialNumber)){
             count++;
             Object[] row = new Object[9];
             row[0]= carDetails;
             row[1]= carDetails.getCarModelName();
             row[2]= carDetails.getCarModelNum();
             row[3]= carDetails.getYearOfManufacturing();
             row[4]= carDetails.getSerialNumber();
             row[5]= carDetails.getLocation();
             row[6]= carDetails.getNumSeats();
             row[7]= carDetails.getCarAvailability();
             row[8]= carDetails.getMainCertiExpiry();

             model.addRow(row);
         }
       }
    }//GEN-LAST:event_btnSearchSerialNumberActionPerformed

    private void btnSearchCarMainCertiExpiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCarMainCertiExpiryActionPerformed
        // TODO add your handling code here:
        String mainCertiExpiry = txtSearchCarMainCertiExpiry.getText();
       
        DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
        model.setRowCount(0);
        int count =0;
        for(CarDetails carDetails : carDetailsHistory.getCarDetailsHistory()){

         if(carDetails.getMainCertiExpiry().equals(mainCertiExpiry)){
             count++;
             Object[] row = new Object[9];
             row[0]= carDetails;
             row[1]= carDetails.getCarModelName();
             row[2]= carDetails.getCarModelNum();
             row[3]= carDetails.getYearOfManufacturing();
             row[4]= carDetails.getSerialNumber();
             row[5]= carDetails.getLocation();
             row[6]= carDetails.getNumSeats();
             row[7]= carDetails.getCarAvailability();
             row[8]= carDetails.getMainCertiExpiry();

             model.addRow(row);
         }
        }
        
    }//GEN-LAST:event_btnSearchCarMainCertiExpiryActionPerformed

    private void btnCarAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarAvailabilityActionPerformed
        // TODO add your handling code here:
        
       String carAvailability = txtSearchCarAvailability.getText();
       
       DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
       model.setRowCount(0);
       int count =0;
       for(CarDetails carDetails : carDetailsHistory.getCarDetailsHistory()){

        if(carDetails.getCarAvailability().equals(carAvailability)){
            count++;
            Object[] row = new Object[9];
            row[0]= carDetails;
            row[1]= carDetails.getCarModelName();
            row[2]= carDetails.getCarModelNum();
            row[3]= carDetails.getYearOfManufacturing();
            row[4]= carDetails.getSerialNumber();
            row[5]= carDetails.getLocation();
            row[6]= carDetails.getNumSeats();
            row[7]= carDetails.getCarAvailability();
            row[8]= carDetails.getMainCertiExpiry();
          
            model.addRow(row);
           }
        }  
    }//GEN-LAST:event_btnCarAvailabilityActionPerformed

    private void btnSearchCarModelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCarModelNameActionPerformed
        // TODO add your handling code here:
       String carModelName = txtSearchCarModelName.getText();
       
       DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
       model.setRowCount(0);
       int count =0;
       for(CarDetails carDetails : carDetailsHistory.getCarDetailsHistory()){

        if(carDetails.getCarModelName().equals(carModelName)){
            count++;
            Object[] row = new Object[9];
            row[0]= carDetails;
            row[1]= carDetails.getCarModelName();
            row[2]= carDetails.getCarModelNum();
            row[3]= carDetails.getYearOfManufacturing();
            row[4]= carDetails.getSerialNumber();
            row[5]= carDetails.getLocation();
            row[6]= carDetails.getNumSeats();
            row[7]= carDetails.getCarAvailability();
            row[8]= carDetails.getMainCertiExpiry();
          
            model.addRow(row);
           }
        }  
    }//GEN-LAST:event_btnSearchCarModelNameActionPerformed

    private void btnSearchLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLocationActionPerformed
        // TODO add your handling code here:
       String location = txtSearchLocation.getText();
       
       DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
       model.setRowCount(0);
       int count =0;
       for(CarDetails carDetails : carDetailsHistory.getCarDetailsHistory()){

        if(carDetails.getLocation().equals(location)){
            count++;
            Object[] row = new Object[9];
            row[0]= carDetails;
            row[1]= carDetails.getCarModelName();
            row[2]= carDetails.getCarModelNum();
            row[3]= carDetails.getYearOfManufacturing();
            row[4]= carDetails.getSerialNumber();
            row[5]= carDetails.getLocation();
            row[6]= carDetails.getNumSeats();
            row[7]= carDetails.getCarAvailability();
            row[8]= carDetails.getMainCertiExpiry();
          
            model.addRow(row);
           }
        }  
    }//GEN-LAST:event_btnSearchLocationActionPerformed

    private void txtSearchNumSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchNumSeatsActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_txtSearchNumSeatsActionPerformed

    private void btnSearchNumSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNumSeatsActionPerformed
        // TODO add your handling code here:
       String numSeats = txtSearchNumSeats.getText();
     
       DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
       model.setRowCount(0);
       int count =0;
       for(CarDetails carDetails : carDetailsHistory.getCarDetailsHistory()){
      
        if(Integer.toString(carDetails.getNumSeats()).equals(numSeats)){
            count++;
            Object[] row = new Object[9];
            row[0]= carDetails;
            row[1]= carDetails.getCarModelName();
            row[2]= carDetails.getCarModelNum();
            row[3]= carDetails.getYearOfManufacturing();
            row[4]= carDetails.getSerialNumber();
            row[5]= carDetails.getLocation();
            row[6]= carDetails.getNumSeats();
            row[7]= carDetails.getCarAvailability();
            row[8]= carDetails.getMainCertiExpiry();
          
            model.addRow(row);
           }
        }  
    }//GEN-LAST:event_btnSearchNumSeatsActionPerformed

    private void btnSearchFirstCarAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFirstCarAvailableActionPerformed
        // TODO add your handling code here:
     
       DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
       model.setRowCount(0);
       int count =0;
       
       int numofavailablecar=0, numofcarnotavailable=0;
       for(CarDetails carDetails : carDetailsHistory.getCarDetailsHistory()){
          
        if(carDetails.getCarAvailability().equals("Yes")){
            count++;
            if(count==1){
            Object[] row = new Object[9];
            row[0]= carDetails;
            row[1]= carDetails.getCarModelName();
            row[2]= carDetails.getCarModelNum();
            row[3]= carDetails.getYearOfManufacturing();
            row[4]= carDetails.getSerialNumber();
            row[5]= carDetails.getLocation();
            row[6]= carDetails.getNumSeats();
            row[7]= carDetails.getCarAvailability();
            row[8]= carDetails.getMainCertiExpiry();
            model.addRow(row);
            }
           }
        }  
    }//GEN-LAST:event_btnSearchFirstCarAvailableActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarAvailability;
    private javax.swing.JButton btnSearchCarMainCertiExpiry;
    private javax.swing.JButton btnSearchCarManufacturer;
    private javax.swing.JButton btnSearchCarModelName;
    private javax.swing.JButton btnSearchCarModelNum;
    private javax.swing.JButton btnSearchFirstCarAvailable;
    private javax.swing.JButton btnSearchLocation;
    private javax.swing.JButton btnSearchNumSeats;
    private javax.swing.JButton btnSearchSerialNumber;
    private javax.swing.JButton btnSearchYearOfManufacturing;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateTitle;
    private javax.swing.JLabel lblNumSeats;
    private javax.swing.JLabel lblSearchCarAvailability;
    private javax.swing.JLabel lblSearchCarAvailability1;
    private javax.swing.JLabel lblSearchCarModelName;
    private javax.swing.JLabel lblSearchCarModelNum;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblSerialNumber1;
    private javax.swing.JLabel lblYearOfManufacturing;
    private javax.swing.JTable tblSearchCarDetails;
    private javax.swing.JTextField txtSearchCarAvailability;
    private javax.swing.JTextField txtSearchCarMainCertiExpiry;
    private javax.swing.JTextField txtSearchCarManufacturer;
    private javax.swing.JTextField txtSearchCarModelName;
    private javax.swing.JTextField txtSearchCarModelNum;
    private javax.swing.JTextField txtSearchLocation;
    private javax.swing.JTextField txtSearchNumSeats;
    private javax.swing.JTextField txtSearchSerialNumber;
    private javax.swing.JTextField txtSearchYearOfManufacturing;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
        model.setRowCount(0);
        
        for (CarDetails carDetails : carDetailsHistory.getCarDetailsHistory()){
            
            Object[] row = new Object[9];
            row[0]= carDetails;
            row[1]= carDetails.getCarModelName();
            row[2]= carDetails.getCarModelNum();
            row[3]= carDetails.getYearOfManufacturing();
            row[4]= carDetails.getSerialNumber();
            row[5]= carDetails.getLocation();
            row[6]= carDetails.getNumSeats();
            row[7]= carDetails.getCarAvailability();
            row[8]= carDetails.getMainCertiExpiry();
          
            model.addRow(row);
            
        }
    }
}
