/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.function.ObjDoubleConsumer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CarDetails;
import model.CarDetailsHistory;

/**
 *
 * @author kinjal
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    CarDetailsHistory carDetailsHistory;
    
    public ViewJPanel(CarDetailsHistory carDetailsHistory) {
        initComponents();
        
        this.carDetailsHistory = carDetailsHistory;
        
        int endYear = Calendar.getInstance().get(Calendar.YEAR);
        this.carDetailsHistory = carDetailsHistory;
        
        //String listYear[] = new String[25];
         jComboManufacturingYear.addItem("--Please Select--");
         for(int year = endYear;  year > endYear-25; year--){
         jComboManufacturingYear.addItem(Integer.toString(year));
        }
         
        txtFleetTime.setText(String.valueOf(LocalDateTime.now()));
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRadioGroup = new javax.swing.ButtonGroup();
        lblCreateTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarDetails = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jComboCarManufacturer = new javax.swing.JComboBox<>();
        txtCarModelNum = new javax.swing.JTextField();
        lblErrorCarModelName = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblErrorSerialNumber = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblErrorCarModelNum = new javax.swing.JLabel();
        btnSaveUpdate = new javax.swing.JButton();
        jComboManufacturingYear = new javax.swing.JComboBox<>();
        txtSerialNumber = new javax.swing.JTextField();
        lblCarModelName = new javax.swing.JLabel();
        noChecked = new javax.swing.JRadioButton();
        lblCreateTitle1 = new javax.swing.JLabel();
        lblMainCertiExpiry = new javax.swing.JLabel();
        txtCarModelName = new javax.swing.JTextField();
        yesChecked = new javax.swing.JRadioButton();
        lblCarManufacturer = new javax.swing.JLabel();
        yesMainCertiExpiryChecked = new javax.swing.JCheckBox();
        lblNumSeats = new javax.swing.JLabel();
        lblCarModelNum = new javax.swing.JLabel();
        lblCarAvailability = new javax.swing.JLabel();
        jComboLocation = new javax.swing.JComboBox<>();
        lblYearOfManufacturing = new javax.swing.JLabel();
        jComboNumSeats = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtFleetTime = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(600, 600));

        lblCreateTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCreateTitle.setForeground(new java.awt.Color(0, 0, 204));
        lblCreateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateTitle.setText("View Car Details");

        tblCarDetails.setBackground(new java.awt.Color(204, 204, 204));
        tblCarDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car Manufacturer", "Car Model Name", "Car Model Number", "Car Manufacturing Year", "Serial Number", "Location", "Number Of Seats", "Availability", "Maintenance Certificate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarDetails);

        btnView.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnView.setText("View");
        btnView.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jComboCarManufacturer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please Select--", "Toyota", "GM", "BMW", "Audi" }));

        txtCarModelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarModelNumActionPerformed(evt);
            }
        });
        txtCarModelNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCarModelNumKeyPressed(evt);
            }
        });

        lblErrorCarModelName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblErrorCarModelName.setForeground(new java.awt.Color(204, 0, 51));

        lblLocation.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblLocation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLocation.setText("Location :");

        lblErrorSerialNumber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblErrorSerialNumber.setForeground(new java.awt.Color(204, 0, 51));

        lblSerialNumber.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNumber.setText("Serial  Number :");

        lblErrorCarModelNum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblErrorCarModelNum.setForeground(new java.awt.Color(204, 0, 51));

        btnSaveUpdate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSaveUpdate.setText("Save");
        btnSaveUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSaveUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUpdateActionPerformed(evt);
            }
        });

        jComboManufacturingYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboManufacturingYearActionPerformed(evt);
            }
        });

        txtSerialNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSerialNumberKeyPressed(evt);
            }
        });

        lblCarModelName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCarModelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarModelName.setText("Car Model Name :");

        noChecked.setBackground(new java.awt.Color(153, 153, 153));
        btnRadioGroup.add(noChecked);
        noChecked.setText("No");

        lblCreateTitle1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCreateTitle1.setForeground(new java.awt.Color(0, 0, 204));
        lblCreateTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateTitle1.setText("View/Update Car Details");

        lblMainCertiExpiry.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblMainCertiExpiry.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMainCertiExpiry.setText(" Maintenance  Certificate ? :");

        txtCarModelName.setEditable(false);
        txtCarModelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarModelNameActionPerformed(evt);
            }
        });
        txtCarModelName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCarModelNameKeyPressed(evt);
            }
        });

        yesChecked.setBackground(new java.awt.Color(153, 153, 153));
        btnRadioGroup.add(yesChecked);
        yesChecked.setSelected(true);
        yesChecked.setText("Yes");

        lblCarManufacturer.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCarManufacturer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarManufacturer.setText("Car Manufacturer :");

        yesMainCertiExpiryChecked.setBackground(new java.awt.Color(153, 153, 153));
        yesMainCertiExpiryChecked.setText("Yes");

        lblNumSeats.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNumSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumSeats.setText("Number of Seats :");

        lblCarModelNum.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCarModelNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarModelNum.setText("Car Model Number :");

        lblCarAvailability.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCarAvailability.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarAvailability.setText("Availability :");

        jComboLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please Select--", "Boston", "Texas", "Arizona", "New York", "New Jersey", "California", "Seatle" }));

        lblYearOfManufacturing.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblYearOfManufacturing.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYearOfManufacturing.setText("Car Manufacturing Year:");

        jComboNumSeats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please Select--", "4", "6" }));

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Fleet Last Update Time :");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtFleetTime.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreateTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblCarAvailability, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblNumSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblSerialNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblYearOfManufacturing, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCarModelNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCarModelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCarManufacturer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblMainCertiExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(yesChecked)
                                                .addGap(29, 29, 29)
                                                .addComponent(noChecked))
                                            .addComponent(yesMainCertiExpiryChecked)
                                            .addComponent(jComboManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCreateTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtCarModelName)
                                                    .addComponent(txtCarModelNum)
                                                    .addComponent(txtSerialNumber)
                                                    .addComponent(jComboNumSeats, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jComboCarManufacturer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jComboLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblErrorSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(lblErrorCarModelNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                                        .addComponent(lblErrorCarModelName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                    .addComponent(txtFleetTime, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 82, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(btnSaveUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblCreateTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFleetTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, Short.MAX_VALUE)
                .addComponent(lblCreateTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboCarManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCarModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCarModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblErrorCarModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblErrorCarModelNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCarModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCarModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYearOfManufacturing, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblErrorSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboNumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesChecked)
                    .addComponent(noChecked)
                    .addComponent(lblCarAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMainCertiExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yesMainCertiExpiryChecked))
                .addGap(18, 18, 18)
                .addComponent(btnSaveUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
       int selectedRowIndex = tblCarDetails.getSelectedRow();
       
       if(selectedRowIndex  < 0) {
           JOptionPane.showMessageDialog(this, "Please select a row to delete the Car details");
           return;
       }
       
       DefaultTableModel model = (DefaultTableModel) tblCarDetails.getModel();
       CarDetails selectedCarDetails = (CarDetails) model.getValueAt(selectedRowIndex, 0);
       carDetailsHistory.removeCarDetails(selectedCarDetails);
       
       JOptionPane.showMessageDialog(this, "Selected Car Details Deleted");
       
       populateTable();
       
       txtFleetTime.setText(String.valueOf(LocalDateTime.now()));
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
       
        JOptionPane.showMessageDialog(this, "Selected Car Details will be viewed");
        
        int selectedRowIndex = tblCarDetails.getSelectedRow();
         if(selectedRowIndex  < 0) {
           JOptionPane.showMessageDialog(this, "Please select a row to view the Car details");
           return;
        }
       
       DefaultTableModel model = (DefaultTableModel) tblCarDetails.getModel();
       CarDetails selectedCarDetails = (CarDetails) model.getValueAt(selectedRowIndex, 0);
       jComboCarManufacturer.setSelectedItem(selectedCarDetails.getCarManufacturer());
       txtCarModelName.setText(selectedCarDetails.getCarModelName());
       txtCarModelNum.setText(selectedCarDetails.getCarModelNum());
       jComboManufacturingYear.setSelectedItem(selectedCarDetails.getYearOfManufacturing());
       txtSerialNumber.setText(String.valueOf(selectedCarDetails.getSerialNumber()));
       jComboLocation.setSelectedItem(selectedCarDetails.getLocation());
       jComboNumSeats.setSelectedItem(String.valueOf(selectedCarDetails.getNumSeats()));
       if(selectedCarDetails.getCarAvailability() == "Yes" ){
           yesChecked.setSelected(true);
           noChecked.setSelected(false);
       }else {
           noChecked.setSelected(true);
           yesChecked.setSelected(false);
       }
       if(selectedCarDetails.getMainCertiExpiry() == "Yes" ){
           yesMainCertiExpiryChecked.setSelected(true);
       }else {
            yesMainCertiExpiryChecked.setSelected(false);
       }
      
        btnSaveUpdate.setEnabled(false);
        jComboCarManufacturer.setEnabled(false);
        txtCarModelName.setEditable(false);
        txtCarModelNum.setEditable(false);
        jComboManufacturingYear.setEnabled(false);
        txtSerialNumber.setEditable(false);
        jComboLocation.setEnabled(false);
        jComboNumSeats.setEnabled(false);
        yesMainCertiExpiryChecked.setEnabled(false);
        yesChecked.setEnabled(false);
        noChecked.setEnabled(false);
       
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtCarModelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarModelNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarModelNumActionPerformed

    private void txtCarModelNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarModelNumKeyPressed
        // TODO add your handling code here:

        String carModelNum = txtCarModelNum.getText();
        String PATTERN = "^[a-zA-Z0-9]+";
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(carModelNum);
        if(!match.matches()){
            lblErrorCarModelNum.setText("Enter a valid Car Model Number!!");
        }else{
            lblErrorCarModelNum.setText(" ");
        }
    }//GEN-LAST:event_txtCarModelNumKeyPressed

    private void btnSaveUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUpdateActionPerformed
        // TODO add your handling code here:
        try{ 
            ArrayList<Integer> unqname = new ArrayList<>();
            for(CarDetails ncar: carDetailsHistory.getCarDetailsHistory()){ 
                if(!(unqname.contains(ncar.getSerialNumber()))){ 
                    unqname.add(ncar.getSerialNumber()); 
                } 
            }

            if(unqname.contains(Integer.parseInt(txtSerialNumber.getText()))) {
                
                JOptionPane.showMessageDialog(this, "Enter unique serial number ");
            }
         } catch(Exception e){ 
             System.out.println("Error in serial no check " +e); 
         }
        
        int selectedRowIndex = tblCarDetails.getSelectedRow();
         if(selectedRowIndex  < 0) {
           JOptionPane.showMessageDialog(this, "Please select a row to update the Car details");
           return;
        }
         
        DefaultTableModel model = (DefaultTableModel) tblCarDetails.getModel();
        
        String carManufacturer = jComboCarManufacturer.getSelectedItem().toString();
        String carModelName = txtCarModelName.getText();
        String carModelNum = txtCarModelNum.getText();
        String yearOfManufacturing = jComboManufacturingYear.getSelectedItem().toString();
        String serialNumber = txtSerialNumber.getText();
        String location = jComboLocation.getSelectedItem().toString();
        String selectedValue = jComboNumSeats.getSelectedItem().toString();

        String carModelNamePattern = "^[a-zA-z]+";
        Pattern expCarModelName = Pattern.compile(carModelNamePattern);

        String serialNumberPattern = "^[0-9]{6}+";
        Pattern expSerialNumber = Pattern.compile(serialNumberPattern);

        String carModelNumPattern = "^[a-zA-Z0-9]+";
        Pattern expCarModelNum = Pattern.compile(carModelNumPattern);
        
        if(txtCarModelName.getText().isEmpty()|| txtCarModelNum.getText().isEmpty() || txtSerialNumber.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "Fields are mandatory !!");
        }else {
            if(carManufacturer == "--Please Select--" || location == "--Please Select--" || selectedValue == "--Please Select--" || yearOfManufacturing == "--Please Select--"){
                JOptionPane.showMessageDialog(this, "Please check the fields !!");
            }else{
                Matcher matchCarModelName = expCarModelName.matcher(txtCarModelName.getText());
                if(!matchCarModelName.matches()){
                    lblErrorCarModelName.setText("Enter a valid car model name!!");
                }else{
                    lblErrorCarModelName.setText(" ");
                    Matcher matchSerialNumber = expSerialNumber.matcher(txtSerialNumber.getText());
                    if(!matchSerialNumber.matches()){
                        lblErrorSerialNumber.setText("Enter a valid Serial Number!!");
                    }else{
                        Matcher matchCarModelNum = expCarModelNum.matcher(txtCarModelNum.getText());
                        lblErrorSerialNumber.setText(" ");
                        if(!matchCarModelNum.matches()){
                            lblErrorCarModelNum.setText("Enter a valid Car Model Number!!");
                        }else{
                            lblErrorCarModelNum.setText(" ");
                            if(selectedRowIndex >= 0){

                                JOptionPane.showMessageDialog(this, "Selected record will be updated!!");

                                model.setValueAt(jComboCarManufacturer.getSelectedItem(), selectedRowIndex, 0);
                                model.setValueAt(txtCarModelName.getText(), selectedRowIndex, 1);
                                model.setValueAt(txtCarModelNum.getText(), selectedRowIndex, 2);
                                model.setValueAt(jComboManufacturingYear.getSelectedItem(), selectedRowIndex, 3);
                                model.setValueAt(txtSerialNumber.getText(), selectedRowIndex, 4);
                                model.setValueAt(jComboLocation.getSelectedItem().toString(), selectedRowIndex, 5);
                                model.setValueAt(jComboNumSeats.getSelectedItem(), selectedRowIndex, 6);
                                
                                if(yesChecked.isSelected()){
                                    model.setValueAt("Yes", selectedRowIndex, 7);
                                }else {
                                    model.setValueAt("No", selectedRowIndex, 7);
                                }

                                if(yesMainCertiExpiryChecked.isSelected()){
                                     model.setValueAt("Yes", selectedRowIndex, 8);
                                }else {
                                     JOptionPane.showMessageDialog(this, "For Maintenance Certificate as nothing is selected its considered to be 'NO' ");
                                     //carDetails.setMainCertiExpiry("No");
                                     model.setValueAt("No", selectedRowIndex, 8);
                                }
                              
                            }else{
                                JOptionPane.showMessageDialog(this, "Records could not be upated!!");
                            }
                        }
                            //clearing the text after the car details are saved
                            jComboCarManufacturer.setSelectedItem("--Please Select--");
                            txtCarModelName.setText("");
                            txtCarModelNum.setText("");
                            jComboManufacturingYear.setSelectedItem("--Please Select--");
                            txtSerialNumber.setText("");
                            jComboLocation.setSelectedItem("--Please Select--");
                            jComboNumSeats.setSelectedItem("--Please Select--");
                            btnRadioGroup.clearSelection();
                            yesMainCertiExpiryChecked.setSelected(false);
                            
                            txtFleetTime.setText(String.valueOf(LocalDateTime.now()));
                        }
                    }
                }
            }
    }//GEN-LAST:event_btnSaveUpdateActionPerformed

    private void jComboManufacturingYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboManufacturingYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboManufacturingYearActionPerformed

    private void txtSerialNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNumberKeyPressed
        // TODO add your handling code here:

        String serialNumber = txtSerialNumber.getText();
        int length = serialNumber.length();

        char c = evt.getKeyChar();

        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<6){
                txtSerialNumber.setEditable(true);
                lblErrorSerialNumber.setText("Serial Numner should be 6 digits!!");
            }else{
                txtSerialNumber.setEditable(false);
                lblErrorSerialNumber.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtSerialNumber.setEditable(true);
            }else{
                txtSerialNumber.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtSerialNumberKeyPressed

    private void txtCarModelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarModelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarModelNameActionPerformed

    private void txtCarModelNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarModelNameKeyPressed
        // TODO add your handling code here:

        char c =evt.getKeyChar();

        if(Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c)){
            lblErrorCarModelName.setText(" ");
            txtCarModelName.setEditable(true);

        }else {
            if(!Character.isLetter(c)){
                // txtName.setEditable(false);
                lblErrorCarModelName.setText("Enter a valid name");
            }
        }
    }//GEN-LAST:event_txtCarModelNameKeyPressed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblCarDetails.getSelectedRow();
         if(selectedRowIndex  < 0) {
           JOptionPane.showMessageDialog(this, "Please select a row to update the Car details");
           return;
        }
         
       DefaultTableModel model = (DefaultTableModel) tblCarDetails.getModel();
       CarDetails selectedCarDetails = (CarDetails) model.getValueAt(selectedRowIndex, 0);
       jComboCarManufacturer.setSelectedItem(selectedCarDetails.getCarManufacturer());
       txtCarModelName.setText(selectedCarDetails.getCarModelName());
       txtCarModelNum.setText(selectedCarDetails.getCarModelNum());
       jComboManufacturingYear.setSelectedItem(selectedCarDetails.getYearOfManufacturing());
       txtSerialNumber.setText(String.valueOf(selectedCarDetails.getSerialNumber()));
       jComboLocation.setSelectedItem(selectedCarDetails.getLocation());
       jComboNumSeats.setSelectedItem(String.valueOf(selectedCarDetails.getNumSeats()));
       if(selectedCarDetails.getCarAvailability() == "Yes" ){
           yesChecked.setSelected(true);
           noChecked.setSelected(false);
       }else {
           noChecked.setSelected(true);
           yesChecked.setSelected(false);
       }
       if(selectedCarDetails.getMainCertiExpiry() == "Yes" ){
           yesMainCertiExpiryChecked.setSelected(true);
       }else {
            yesMainCertiExpiryChecked.setSelected(false);
       }
      
        btnSaveUpdate.setEnabled(true);
        jComboCarManufacturer.setEnabled(true);
        txtCarModelName.setEditable(true);
        txtCarModelNum.setEditable(true);
        jComboManufacturingYear.setEnabled(true);
        txtSerialNumber.setEditable(true);
        jComboLocation.setEnabled(true);
        jComboNumSeats.setEnabled(true);
        yesMainCertiExpiryChecked.setEnabled(true);
        yesChecked.setEnabled(true);
        noChecked.setEnabled(true);

    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.ButtonGroup btnRadioGroup;
    private javax.swing.JButton btnSaveUpdate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> jComboCarManufacturer;
    private javax.swing.JComboBox<String> jComboLocation;
    private javax.swing.JComboBox<String> jComboManufacturingYear;
    private javax.swing.JComboBox<String> jComboNumSeats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarAvailability;
    private javax.swing.JLabel lblCarManufacturer;
    private javax.swing.JLabel lblCarModelName;
    private javax.swing.JLabel lblCarModelNum;
    private javax.swing.JLabel lblCreateTitle;
    private javax.swing.JLabel lblCreateTitle1;
    private javax.swing.JLabel lblErrorCarModelName;
    private javax.swing.JLabel lblErrorCarModelNum;
    private javax.swing.JLabel lblErrorSerialNumber;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMainCertiExpiry;
    private javax.swing.JLabel lblNumSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblYearOfManufacturing;
    private javax.swing.JRadioButton noChecked;
    private javax.swing.JTable tblCarDetails;
    private javax.swing.JTextField txtCarModelName;
    private javax.swing.JTextField txtCarModelNum;
    private javax.swing.JTextField txtFleetTime;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JRadioButton yesChecked;
    private javax.swing.JCheckBox yesMainCertiExpiryChecked;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblCarDetails.getModel();
        model.setRowCount(0);
        
        for (CarDetails carDetails : carDetailsHistory.getCarDetailsHistory()){
            
            Object[] row = new Object[9];
            row[0]= carDetails;
            row[1]= carDetails.getCarModelName();
            row[2]= carDetails.getCarModelNum();
            row[3]= carDetails.getYearOfManufacturing();
            row[4]= carDetails.getSerialNumber();
            row[5]= carDetails.getLocation();
            row[6]= carDetails.getNumSeats();
            row[7]= carDetails.getCarAvailability();
            row[8]= carDetails.getMainCertiExpiry();
          
            model.addRow(row);
            
        }
    }
}
